var abbreviationDict = {
  'USA': 'United States',
  'England': 'United Kingdom',
  'U.K.': 'United Kingdom',
  'UK': 'United Kingdom',
  'U.K': 'United Kingdom',
  'United Kingdom (Great Britain)': 'United Kingdom',
  'Great Britain': 'United Kingdom',
  'Great Brittan': 'United Kingdom',
  'GB': 'United Kingdom',
  'GGY': 'United Kingdom',
  'Russia': 'Russian Federation',
  'Tanzania': 'Tanzania, United Republic Of',
  'Congo (Dem. Rep.)': 'Democratic Republic Of Congo',
  'Congo Dem. Rep.': 'Democratic Republic Of Congo',
  'Congo (Rep.)': 'Republic Of Congo',
  'Congo Rep.': 'Republic Of Congo',
  'Sao Tome & Principe': 'Sao Tome and Principe',
  'Guinea Bissau': 'Guinea-bissau',
  'Korea (South)': 'Korea, Republic Of',
  'Korea South': 'Korea, Republic Of',
  'Korea (North)': 'Korea, Democratic People\'s Republic Of',
  'Korea North': 'Korea, Democratic People\'s Republic Of',
  'Syria': 'Syrian Arab Republic',
  'Brunei': 'Brunei Darussalam',
  'Laos': 'Lao People\'s Democratic Republic',
  'Iran': 'Iran, Islamic Republic Of',
  'Lucia': 'Saint Lucia',
  'St Lucia': 'Saint Lucia',
  'Antigua & Barbuda': 'Antigua And Barbuda',
  'St Kitts & Nevis': 'Saint Kitts And Nevis',
  'Samoa (American)': 'American Samoa',
  'Samoa (western)': 'Samoa',
  'Cote d\'Ivoire': 'Côte d\'Ivoire',
  'Antigua and Barbuda': 'Antigua And Barbuda',
  'Bosnia and Herzegovina': 'Bosnia & Herzegovina',
  'Cocos Islands': 'Cocos (Keeling) Islands',
  'Democratic Republic of the Congo': 'Democratic Republic Of Congo',
  'Isle of Man': 'Isle Of Man',
  'Ivory Coast': 'Côte d\'Ivoire',
  'Micronesia': 'Micronesia, Federated States Of',
  'North Korea': 'Korea, Republic Of',
  'Republic of the Congo': 'Republic Of Congo',
  'Saint Helena': 'Saint Helena, Ascension And Tristan Da Cunha',
  'Saint Pierre and Miquelon': 'Saint Pierre And Miquelon',
  'Saint Vincent and the Grenadines': 'Saint Vincent And The Grenadines',
  'South Korea': 'Korea, Democratic People\'s Republic Of',
  'Svalbard and Jan Mayen': 'Svalbard And Jan Mayen',
  'Trinidad and Tobago': 'Trinidad And Tobago',
  'Turks and Caicos Islands': 'Turks And Caicos Islands',
  'U.S. Virgin Islands': 'Virgin Islands (US)',
  'Vatican': 'Vatican City State',
  'Wallis and Futuna': 'Wallis And Futuna',
  'Republic of Macedonia': 'Macedonia, The Former Yugoslav Republic Of',
  'Macedonia': 'Macedonia, The Former Yugoslav Republic Of',
  'Jan Mayen': 'Svalbard And Jan Mayen'
}

module.exports = abbreviationDict
