var sfCountries = {
  'Sint Eustatius': 'Bonaire, Saint Eustatius And Saba',
  'Bonaire': 'Bonaire, Saint Eustatius And Saba',
  'Saba': 'Bonaire, Saint Eustatius And Saba',
  'Kingdom of Navarre': '',
  'Timor-Leste': 'Timor-Leste, Democratic Republic of',
  'Saint Martin (French Part)': 'Saint Martin',
  'South Georgia and The South Sandwich Islands': 'South Georgia And The South Sandwich Islands',
  'Bonaire, Sint Eustatius and Saba': 'Bonaire, Saint Eustatius And Saba',
  'Saint Barthelemy': 'Saint Barthélemy',
  'Aland Islands': 'New Zealand',
  'Palestine': 'Palestinian Territory, Occupied',
  'Saint Kitts and Nevis': 'Saint Kitts And Nevis',
  'Saint Pierre & Miquelon': 'Saint Pierre And Miquelon',
  'Saint Vincent & Grenadines': 'Saint Vincent And The Grenadines',
  'Trinidad & Tobago': 'Trinidad And Tobago',
  'Turks & Caicos Islands': 'Turks And Caicos Islands',
  'Venezuela': 'Venezuela, Bolivarian Republic Of',
  'US Virgin Islands': 'Virgin Islands (US)',
  'United Kingdom (inc Northern Ireland)': 'United Kingdom',
  'Bolivia': 'Bolivia, Plurinational State Of',
  'Bosnia And Herzegovina': 'Bosnia & Herzegovina',
  'Central African Rep.': 'Central African Republic',
  'Congo (Brazzaville)': 'Republic Of Congo',
  'Holy See (Vatican City)': 'Vatican City State',
  'Congo, The Democratic Republic of': 'Democratic Republic Of Congo',
  'East Timor': 'Timor-Leste, Democratic Republic of',
  'Korea, Dem. People\'s Rep.': 'Korea, Democratic People\'s Republic Of',
  'Macau': 'Macao',
  'Micronesia, Fed. States of': 'Micronesia, Federated States Of',
  'Svalbard And Jan Mayen Islands': 'Svalbard And Jan Mayen',
  'British Virgin Islands': 'Virgin Islands (British)',
  'Syrian Arab Rep.': 'Syrian Arab Republic',
  'Tanzania, United Rep. of': 'Tanzania, United Republic Of',
  'Vietnam': 'Viet Nam',
  'Wallis & Futuna': 'Wallis And Futuna',
  'Cape Verde': 'Cabo Verde',
  'Guinea-Bissau': 'Guinea-bissau',
  'Heard And McDonald Islands': 'Heard Island And McDonald Islands',
  'Iran, Islamic Rep. of': 'Iran, Islamic Republic Of',
  'Ireland (Southern)': 'Ireland',
  'Korea, Rep. of': 'Korea, Republic Of',
  'Lao People\'s Dem. Rep.': 'Lao People\'s Democratic Republic',
  'Libyan Arab Jamahiriya': 'Libya',
  'Macedonia': 'Macedonia, The Former Yugoslav Republic Of',
  'Man, Isle of': 'Isle Of Man',
  'Moldova, Rep.': 'Moldova',
  'Myanmar (Burma)': 'Myanmar',
  'Pitcairn Island': 'Pitcairn',
  'Sao Tome & Principe': 'São Tomé and Príncipe',
  'St Helena': 'Saint Helena, Ascension And Tristan Da Cunha',
  'Cayenne': 'Cayman Islands',
  'United States of America': 'United States'
}

module.exports = sfCountries
